os: osx
osx_image: xcode11.3
language: objective-c
script:
  - set -o pipefail && xcodebuild -project "PetMyPet.xcodeproj" -scheme "PetMyPet" -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty

branches:
 only:
 - master
